# Generated by Django 5.1 on 2026-02-06 04:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('sport_rank', models.CharField(max_length=50, verbose_name='Разряд/звание')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отделения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вида тренировки')),
            ],
            options={
                'verbose_name': 'Вид тренировки',
                'verbose_name_plural': 'Виды тренировок',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('coach', 'Тренер'), ('manager', 'Руководитель'), ('methodist', 'Методист')], max_length=20, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=100, verbose_name='Тип документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file_path', models.FileField(upload_to='docs/', verbose_name='Файл')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Административный документ',
                'verbose_name_plural': 'Административные документы',
            },
        ),
        migrations.CreateModel(
            name='AthleteRankAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_rank', models.CharField(max_length=50, verbose_name='Присвоенный разряд')),
                ('assignment_date', models.DateField(blank=True, null=True, verbose_name='Дата присвоения')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.athlete', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Присвоение разряда спортсмену',
                'verbose_name_plural': 'Присвоения разрядов спортсменам',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название соревнования')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('location', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('level', models.CharField(max_length=50, verbose_name='Уровень')),
                ('protocol', models.FileField(blank=True, null=True, upload_to='protocols/', verbose_name='Протокол соревнований')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен'), ('approved', 'Утвержден'), ('returned', 'На доработку')], default='draft', max_length=20, verbose_name='Статус')),
                ('review_comment', models.TextField(blank=True, verbose_name='Комментарий методиста')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='sportSchool.coach', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='Разряд/звание')),
                ('weight_category', models.CharField(blank=True, max_length=50, verbose_name='Весовая категория')),
                ('is_participant', models.BooleanField(default=False, verbose_name='Участник без места')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.athlete', verbose_name='Спортсмен')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.coach', verbose_name='Тренер')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.competition', verbose_name='Соревнование')),
            ],
            options={
                'verbose_name': 'Результат соревнования',
                'verbose_name_plural': 'Результаты соревнований',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('level', models.CharField(choices=[('beginner', 'Начальная подготовка'), ('training', 'Учебно-тренировочный'), ('improvement', 'Совершенствование спортивного мастерства'), ('high', 'Высшее спортивное мастерство')], default='beginner', max_length=20, verbose_name='Уровень группы')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='sportSchool.coach', verbose_name='Тренер группы')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.group', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='RankAssignmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер приказа')),
                ('order_date', models.DateField(verbose_name='Дата приказа')),
                ('document', models.FileField(blank=True, null=True, upload_to='rank_orders/', verbose_name='Файл приказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('athletes', models.ManyToManyField(related_name='rank_orders', through='sportSchool.AthleteRankAssignment', to='sportSchool.athlete', verbose_name='Спортсмены')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Приказ о присвоении разряда',
                'verbose_name_plural': 'Приказы о присвоении разрядов',
            },
        ),
        migrations.AddField(
            model_name='athleterankassignment',
            name='rank_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.rankassignmentorder', verbose_name='Приказ'),
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_hours', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.group')),
            ],
            options={
                'verbose_name': 'Тренировочный план',
                'verbose_name_plural': 'Тренировочные планы',
                'unique_together': {('group', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='athleterankassignment',
            unique_together={('athlete', 'rank_order')},
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(verbose_name='Квартал')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('competition_count', models.IntegerField(default=0, verbose_name='Количество соревнований')),
                ('participant_count', models.IntegerField(default=0, verbose_name='Количество участников')),
                ('victories_count', models.IntegerField(default=0, verbose_name='Количество побед')),
                ('prize_count', models.IntegerField(default=0, verbose_name='Количество призовых мест')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'unique_together': {('department', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал')], max_length=20)),
                ('absence_reason', models.CharField(blank=True, max_length=200)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.athlete')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='sportSchool.trainingplan')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'unique_together': {('athlete', 'training_plan')},
            },
        ),
        migrations.CreateModel(
            name='TrainingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_hours', to='sportSchool.trainingplan')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSchool.trainingtype')),
            ],
            options={
                'verbose_name': 'Тренировочные часы',
                'verbose_name_plural': 'Тренировочные часы',
                'unique_together': {('training_plan', 'training_type')},
            },
        ),
    ]
