# Generated by Django 5.2.9 on 2026-03-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportSchool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionresult',
            name='rank',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='sportSchool.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='sportSchool.group'),
        ),
    ]
