# Generated by Django 5.2.9 on 2026-03-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportSchool', '0002_remove_competitionresult_rank_alter_athlete_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='sport_rank',
        ),
        migrations.RemoveField(
            model_name='rankassignmentorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rankassignmentorder',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='athleterankassignment',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_assignments', to='sportSchool.athlete', verbose_name='Спортсмен'),
        ),
    ]
